### PR TITLE
Guzzle 7.0 Support

### PR DESCRIPTION
**Pull request by blankse**

### CODE REVIEW

**Comment by jkphl** [comment]
I'll try to merge this during the weekend!

**Comment by blankse** [comment]
@jkphl @rvanlaak Can you add here also a new release?

**Comment by rvanlaak** [comment]
I can't, as I'm not a maintainer of this library. So, tagging is up to @jkphl

**Comment by jkphl** [comment]
@blankse I'm sorry but I can't offer any mental bandwidth and capacity for the next couple of weeks / months (which is what would probably be needed in order to review this thoroughly). If that's an option, @rvanlaak, I'd make you a maintainer and trust you to create a new tag / release. Please let me know.

**Comment by rvanlaak** [comment]
@jkphl feel free to add me as maintainer, or setup the organization as we discussed by email a while ago.

@blankse could you verify the codebase agains the UPGRADING log to get this PR merged asap? https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by jkphl** [comment]
@rvanlaak Yeah, we started talking about it at some point, but AFAIR I sent you a couple of questions and never got your response, so I eventually deleted the item from my to-do list. We can pick up on this at a later point again — for the moment I invited you as a collaborator (I hope this is doing the trick, pls let me know if not). Thank you both!

**Comment by blankse** [comment]
@rvanlaak The Guzzle Client is only used here:
https://github.com/jkphl/dom-factory/blob/master/src/Domfactory/Infrastructure/Dom.php#L67
The get method and the response getBody method should also be okay in 7.0

**Pull request merged**
